# Generated by Django 3.0.8 on 2020-07-04 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamado',
            old_name='chamado',
            new_name='codigo',
        ),
    ]
